version: '3.3'

services:
  web:
    container_name: apirest
    build: ./server
    restart: always
    ports:
      - "80:5000"
    networks:
      - networkapi.
    volumes:
      - /proc:/usr/src/app/lecturas

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - networkapi.
    volumes:
      - ./mongo:/data/db
    logging:
      driver: none

    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root

networks:
  networkapi.:
    driver: "bridge"